In [1]:
import numpy as np
import nilearn
import pandas as pd
import os
import pycaret
from nilearn.connectome import sym_matrix_to_vec
import pickle
import json
from modeling_utils import *
from pycaret.classification import *

# Prepare Data for Pycaret

In [2]:
#data_paths = json.load(open('data_paths.json', 'r'))

data_paths = {
"COBRE-SCZ": "/Users/VictoriaShevchenko/Documents/PhD/SCZ/COBRE/clean_data/SCZ",
"COBRE-controls": "/Users/VictoriaShevchenko/Documents/PhD/SCZ/COBRE/clean_data/controls",
"LA5c": "/Users/VictoriaShevchenko/Documents/PhD/SCZ/LA5c/clean_data",
"SRPBS-1600-KTT": "/Users/VictoriaShevchenko/Documents/PhD/SCZ/SRPBS_1600/KTT/clean_data",
}

In [3]:
diagnosis_mapping = {
    'CONTROL': 0,
    'SCHZ': 1,
    'Schizophrenia_Strict': 1,
    'No_Known_Disorder': 0,
    4: 1,
    0: 0
}

In [8]:
participants = prepare_data_csv(data_paths, diag_mapping = diagnosis_mapping)
data = participants.drop(columns=['participant_id', 'path'])

In [9]:
data

     diagnosis  age  sex         dataset
1            1   30    0           COBRE
2            1   32    1           COBRE
3            1   34    0           COBRE
4            1   20    1           COBRE
5            1   56    1           COBRE
..         ...  ...  ...             ...
554          0   31    0  SRPBS-1600-KTT
555          0   28    0  SRPBS-1600-KTT
556          0   32    0  SRPBS-1600-KTT
557          0   39    0  SRPBS-1600-KTT
558          0   28    0  SRPBS-1600-KTT

[442 rows x 4 columns]

# Model Selection

In [10]:
exp = setup(data, target = 'diagnosis', session_id = 123)

In [9]:
best_model = compare_models(n_select = 14)

Processing:   0%|          | 0/78 [00:00<?, ?it/s]

In [10]:
pull()

,Model,Accuracy,AUC,Recall,Prec.,F1,Kappa,MCC,TT (Sec)
nb,Naive Bayes,0.6376,0.6465,0.4803,0.5074,0.4904,0.2111,0.2128,0.043
dummy,Dummy Classifier,0.6349,0.5000,0.0000,0.0000,0.0000,0.0000,0.0000,0.040
ada,Ada Boost Classifier,0.6163,0.5993,0.2098,0.4867,0.2774,0.0680,0.0878,0.076
knn,K Neighbors Classifier,0.6107,0.6131,0.4455,0.4714,0.4507,0.1517,0.1573,0.057
lda,Linear Discriminant Analysis,0.6070,0.6435,0.2182,0.4812,0.2947,0.0596,0.0802,0.042
lr,Logistic Regression,0.6069,0.6431,0.2182,0.4783,0.2940,0.0590,0.0791,0.512
lightgbm,Light Gradient Boosting Machine,0.6045,0.6120,0.4023,0.4570,0.4205,0.1252,0.1286,0.061
ridge,Ridge Classifier,0.6039,0.0000,0.2098,0.4712,0.2856,0.0501,0.0701,0.031
gbc,Gradient Boosting Classifier,0.5982,0.5925,0.3015,0.4029,0.3277,0.0679,0.0684,0.073
et,Extra Trees Classifier,0.5676,0.5718,0.3015,0.3852,0.3314,0.0228,0.0245,0.094
dt,Decision Tree Classifier,0.5616,0.5625,0.3432,0.3925,0.3594,0.0316,0.0329,0.040
rf,Random Forest Classifier,0.5585,0.5820,0.3848,0.3895,0.3815,0.0409,0.0418,0.096
qda,Quadratic Discriminant Analysis,0.5578,0.5549,0.4227,0.3852,0.3294,0.0551,0.0706,0.043
svm,SVM - Linear Kernel,0.5491,0.0000,0.5803,0.3037,0.3907,0.0992,0.1237,0.032
xgboost,Extreme Gradient Boosting,0.5403,0.5734,0.3515,0.3635,0.3495,-0.0022,-0.0001,0.059

In [11]:
lr = create_model('lr')

In [12]:
lr = pull()

In [22]:
lr.loc["Mean"]["Accuracy"]

0.5792